apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "viacep"
  description: "Artifacts generator via Spec."
  annotations:
    github.com/project-slug: veecode-homolog/viacep
    backstage.io/techdocs-ref: dir:..
    # github.com/workflows: publish.yml,remove.yml
    kong-manager/service-name: 8453e77d-12a5-4120-a821-dad80478ce49
    kong-manager/instance: kong-demo
    kong-manager/spec: openapi-swagger.yaml
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
  providesApis:
    - viacep
